export { default as App } from "./carcomponent";
export { default as Getmyapi } from "./getApi";
export { default as Movie } from "./movie";
export { default as movies } from "./movies";
export { default as MyForm } from "./myform";
export { default as Mystate } from "./stateApp";
export { default as Rout } from "./router";
export { default as Pagination } from "./pagination";
export { default as MyReducer } from "./useReducer.js";
